version: '3.5'
services:
  db1:
    image: postgres:14.3-alpine3.15
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - net1
  nginx:
    image: nginx:stable-alpine3.20-slim
    restart: always
    ports:
      - "8080:80"
    environment:
      - DJANGO_HOST=web
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./www:/www
    networks:
      - net1
  web-v:
    container_name: store-v4
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db1
    restart: unless-stopped
    volumes:
      - .:/app
      - ./www:/www
    entrypoint: [ "bash", "-c", "python manage.py makemigrations
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000 
      && manage.py collectstatic --noinput" ]
    networks:
      - net1
networks:
  net1:
    driver: bridge