version: '3.5'
services:
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    ports:
      - "6379:6379"
    command: [redis-server, /usr/local/etc/redis.conf]
    networks:
    - net1
  celery:
    build: .
    entrypoint: celery
    command: -A diploma_app.celery worker --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: "diploma_app.settings"
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
    - .:/app
    links:
    - redis
    depends_on:
    - redis
    - web-0
    networks:
    - net1
  db1:
    image: postgres:14.3-alpine3.15
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    networks:
      - net1
  nginx:
    image: nginx:stable-alpine3.20-slim
    restart: always
    ports:
      - "8080:80"
    environment:
      - DJANGO_HOST=web
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./www:/www
    networks:
      - net1
  web-0:
    container_name: store-v00
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db1
      VK_APP_ID: ${VK_APP_ID}
    restart: unless-stopped
    volumes:
      - .:/app
      - ./www:/www
    entrypoint: [ "bash", "-c", "python manage.py makemigrations
      && python manage.py migrate 
      && python manage.py runsslserver 0.0.0.0:8000
      && manage.py collectstatic --noinput" ]
    networks:
      - net1
networks:
  net1:
    driver: bridge